"""
A collection of rap phrases and lyrics for use in the Rap Writer application.

This module contains a list of pre-written rap phrases that can be used as
inspiration or building blocks for generating rap lyrics. The phrases cover
various themes common in rap music, including success, struggle, ambition,
wealth, and street life.

The 'all_phrases' list can be imported and used in other parts of the
application, such as for providing suggestions to users or as seed phrases
for AI-generated lyrics.

Example:
    from all_phrases import all_phrases
    random_phrase = random.choice(all_phrases)
    print(f"Here's an inspirational rap phrase: {random_phrase}")0-

Note:
    This list is not exhaustive and can be expanded or modified to include
    more diverse themes or styles of rap phrases.
"""
from typing import List


all_phrases: List[str] = [

    "Riding through the city with my woes",
    "Money on my mind, gotta hustle till I shine",
    "Straight outta the gutter, now I'm living lavish",
    "From the bottom to the top, now the view is fantastic",
    "Every day I'm grinding, chasing dreams, no sleep",
    "Started from the block, now we on the billboard",
    "I got 99 problems but a beat ain't one",
    "Keep your head up, stay strong through the storm",
    "Living my best life, no regrets, no apologies",
    "In the studio cooking, turning beats into flames",
    "From rags to riches, this is my testimony",
    "I'm the king of my city, crown me with glory",
    "Success is the mission, failure ain't an option",
    "Mic check, one-two, I'm about to blow",
    "Chasing paper like it's running from me",
    "I'm a beast on the mic, unleash the lyrical fury",
    "Money, power, respect, that's the code that we live by",
    "Dream big, grind harder, make it happen",
    "No new friends, just me and my day ones",
    "Turn my pain into power, that's the ultimate flex",
    "I'm the lyrical chef, cooking bars in the kitchen",
    "Rap game on lock, got the combination",
    "Every rhyme a masterpiece, call me Da Vinci",
    "On this beat, I'm Picasso with a vision",
    "Breaking boundaries, no limits to my ambition",
    "I spit fire, leave the mic in ashes",
    "Hip-hop savior, resurrected the classics",
    "Flow so smooth, it's like water in motion",
    "My words are bullets, my tongue is the trigger",
    "Haters talk, but I'm too busy counting figures",
    "Every verse I spit, it's like painting a picture",
    "Rap god, divine flow, I'm a scripture",
    "Spitting knowledge, my bars are like a lecture",
    "Can't handle my style, too much pressure",
    "Lyrics cut deep, sharper than a razor",
    "In this rap game, I'm the trailblazer",
    "Voice like thunder, flow like a river",
    "I see my haters shiver, I'm a rap deliverer",
    "Dropped the mic, now they're picking up their pride",
    "Too fly for gravity, I can't be denied",
    "Words so powerful, they spark a revolution",
    "Cash rules everything around me, C.R.E.A.M.",
    "Stacks on stacks, money talk, wealth attract",
    "Counting up my blessings and my bank rolls",
    "Get rich or die tryin'",
    "Making money moves, gotta keep my circle tight",
    "Hustle hard, stack paper, invest smart",
    "Big dreams, big checks, big investments",
    "Fortune favors the bold, I'm living proof",
    "I want the money, money and the cars, cars and the clothes",
    "Million-dollar mindset, billionaire grind",
    "I'm in the penthouse, views from the top",
    "Cash flow steady, never going broke again",
    "Paper chasing till I'm racing in a Lambo",
    "Financial freedom, now that's real power",
    "Get the bag, secure the future, make it last",
    "Making deals with execs while I'm sipping champagne",
    "Every dollar a soldier in my financial army",
    "Turned a dream into reality, check my portfolio",
    "Invested in myself, now my stock's on the rise",
    "Generational wealth, building bricks from my grind",
    "Cash flow coming in, like the tide's on my side",
    "Cryptocurrency king, I'm stacking digital gold",
    "Passive income streams, while I sleep I'm getting paid",
    "Gold chains, private planes, I'm in the billionaire's club",
    "Hustle so hard, they think I'm running a marathon",
    "From rags to riches, now I'm swimming in riches",
    "Dressed in designer, I'm living how I envisioned",
    "Made a fortune, now I'm sitting on a golden throne",
    "Financial empire, I built it on my own",
    "Net worth rising, like stocks on the market",
    "I turned my dreams into assets, now I'm profiting",
    "Financial independence, I'm living my vision",
    "Built a legacy, now my name's a tradition",
    "My bank account smiles every time I make a decision",
    "Money magnet, every move is precision",
    "From the struggle to the hustle, I earned my place",
    "Survived the streets, now I'm living my dreams",
    "Turned my scars into stars, that's my story",
    "Raised in the hood, made it out of poverty",
    "Life's a battle, I'm a soldier on the front line",
    "Can't stop, won't stop, I've been through worse",
    "I learned from the pain, now I'm stronger than ever",
    "From the trenches to the throne, my story's untold",
    "Every loss is a lesson, every struggle is a blessing",
    "I'm a product of the streets, but I beat the odds",
    "Hard times taught me how to hustle harder",
    "Surviving and thriving, that's my daily mantra",
    "Life tried to break me, but I built back better",
    "No more rainy days, I've found my sunshine",
    "When life knocks you down, get up swinging",
    "The hood raised me, but it never fazed me",
    "Found light in the darkness, now I'm blazing",
    "The struggle's my story, every chapter's a victory",
    "From sleeping on floors to walking on marble",
    "I was born a fighter, life made me a warrior",
    "Through the fire, I rose like a phoenix from the ashes",
    "Battled my demons, now I'm blessed beyond measure",
    "Life threw me lemons, I made a business from lemonade",
    "Survived the worst storms, now I dance in the rain",
    "Turned my pain into poetry, my wounds into wisdom",
    "Found hope in the hopeless, turned loss into gain",
    "I walked through the valley, now I'm on the mountain",
    "Defied every obstacle, now I'm breaking the chains",
    "Turned my trials into triumphs, I rewrote my fate",
    "From despair to victory, I built my own lane",
    "I survived the struggle, now I'm thriving in the rain",
    "Life tried to drown me, but I learned how to swim",
    "Built resilience from every hardship I endured",
    "Turned my back on the darkness, now I'm the light",
    "Heart on my sleeve, love scars from the past",
    "You were my everything, now you're just a memory",
    "Love and loyalty, that's my code of honor",
    "Broken hearts and late-night texts, I've been there",
    "Ride or die chick, she's my Bonnie, I'm her Clyde",
    "Love hurts, but losing you hurts even more",
    "You were my dream, now you're my nightmare",
    "Chasing love, but it's running away from me",
    "Emotions run deep, like rivers in the night",
    "Love me or leave me, just don't deceive me",
    "I gave you my all, but you wanted more",
    "Heartbreak hotel, checking out tonight",
    "Your love was poison, but I drank it anyway",
    "Cupid's arrow missed, but I found myself instead",
    "Love's a battlefield, but I'm a warrior at heart",
    "We were a perfect match, now we're a burnt-out flame",
    "Fell for you hard, now I'm falling apart",
    "Our love was a masterpiece, now it's a blank canvas",
    "You took my heart, left me with the pieces",
    "In the game of love, I played my part, you cheated",
    "Tears fall like rain, but I'm dancing through the pain",
    "Lost in your love, but now I'm finding my way back",
    "I was your king, but you dethroned me with lies",
    "Your love was a drug, and now I'm going through withdrawal",
    "Built a castle of dreams, but you turned it to dust",
    "Your love was a symphony, now it's just a solo",
    "We wrote a love story, now it's just an epilogue",
    "Your kisses were like honey, now they're bitter wine",
    "Love blinded me, but now I see the truth",
    "You were the beat in my heart, now it's out of tune",
    "Found myself in your love, but lost in your lies",
    "Love's a gamble, but you played me for a fool",
    "Built bridges of trust, but you burned them all down",
    "Our love was a journey, but you took the wrong turn",
    "Street dreams made of these",
    "On the block with the Glock, ready to rock",
    "Survivor of the concrete jungle",
    "In the streets, respect is the ultimate currency",
    "Trap life, but I'm aiming for the high life",
    "The streets don't love you, but I had to learn",
    "Riding dirty, but my soul's clean",
    "Hustle hard, trust no one, keep your circle small",
    "Living life on the edge, one foot in the grave",
    "Street knowledge, but my dreams are Ivy League",
    "In the hood, every day is a struggle for survival",
    "From dope deals to record deals, I flipped the script",
    "Corner store to corporate board, that's my journey",
    "Raised by the streets, but I own my future",
    "In the trap, making moves like a chess player",
    "Survival of the fittest, I'm the last man standing",
    "Street smart, book smart, I'm a double threat",
    "Living by the code, die by the code, that's the motto",
    "Made it out the trenches, now I'm trench coat fancy",
    "From street lights to bright lights, I made the transition",
    "Surrounded by wolves, but I run with lions",
    "In the belly of the beast, but I'm the beast tamer",
    "Street life taught me lessons school couldn't teach",
    "From street corners to corner offices, I broke the cycle",
    "Made my first million, but I'll never forget the streets",
    "Grew up on the block, now I'm breaking blocks of stocks",
    "From flipping bricks to flipping businesses",
    "I'm a street scholar, learned from the best hustlers",
    "The corner was my classroom, now I'm teaching economics",
    "Rags to riches, but the streets stay in my blood",
    "My life was a hustle, now it's a success story",
    "From a dime bag to big bags, now I'm the man",
    "Street certified, I turned my struggle into a brand",
    "Taught by the streets, but now I'm the professor",
    "From the shadows of the hood to the spotlight of fame",
    "Turn up the music, let the good times roll",
    "In the VIP, popping bottles with my crew",
    "Tonight we live like there's no tomorrow",
    "Dance floor packed, DJ spinning the hits",
    "Party all night, sleep all day",
    "Champagne showers and late-night hours",
    "Hit the club, make it rain, then disappear",
    "Good vibes only, leave your worries at the door",
    "Let's get wild, lose control, and have fun",
    "Living for the weekend, every day's a Friday",
    "Dancing under the neon lights, feeling free",
    "Life's a party, so let's dance like nobody's watching",
    "Bottle service, VIP section, living large",
    "From dusk till dawn, we're breaking all the rules",
    "Club lights flashing, our spirits are high",
    "Pop the cork, let's toast to life",
    "Dance till we drop, till the morning light",
    "Glow sticks, good drinks, we're the life of the night",
    "DJ, turn it up, make this place ignite",
    "Feeling like a star under these disco lights",
    "On the rooftop, looking at city lights, feeling right",
    "Every night's a movie, we're the stars of the show",
    "Bass thumping, heart pumping, feeling the flow",
    "Sipping on cocktails, enjoying the show",
    "Living like rockstars, every night's a blowout",
    "From Miami to Ibiza, we party worldwide",
    "Champagne flutes, luxury suites, we live in the sky",
    "Dancing on tables, breaking the norms, wild and free",
    "Confetti in the air, happiness everywhere",
    "Limousines and party scenes, that's how we roll",
    "Private jets to the next set, we never settle",
    "Shots lined up, we're on another level",
    "Let the rhythm take over, lose control to the sound",
    "Sunrise parties on the beach, where we feel the heat",
    "No regrets, no drama, just living our dreams",
    "Keep grinding, the world is yours for the taking",
    "Dream big, work hard, stay humble",
    "Every setback is a setup for a comeback",
    "Rise above, never let them see you down",
    "Stay true to yourself, no matter the pressure",
    "Success is a journey, not a destination",
    "Believe in your vision, even when they doubt",
    "Champions keep playing until they get it right",
    "Your only limit is the one you set yourself",
    "Push past the pain, greatness awaits",
    "Success requires hard work, there's no shortcut",
    "Stay focused, stay driven, stay winning",
    "You have the power to change your story",
    "No excuses, just results, that's the mindset",
    "If you can dream it, you can achieve it",
    "In the face of adversity, keep pushing forward",
    "Your grind is your weapon, your will is your shield",
    "Every failure is a lesson, every win is a step closer",
    "Keep your circle small, your vision large",
    "Doubt kills more dreams than failure ever will",
    "Embrace the struggle, it's shaping your success",
    "The only way to achieve the impossible is to believe it is possible",
    "Set your goals high, and don't stop till you get there",
    "Determination is the fuel, passion is the engine",
    "Wake up with determination, go to bed with satisfaction",
    "You are stronger than you think, braver than you believe",
    "Dream without fear, love without limits, live without regrets",
    "Obstacles are opportunities in disguise, face them head-on",
    "Your journey is unique, embrace it, own it",
    "Every great story begins with a challenge, accept it",
    "Your grind defines you, keep the hustle alive",
    "Believe in the power of your dreams, they know the way",
    "Turn your wounds into wisdom, your pain into power",
    "Greatness isn't given, it's earned with hard work and dedication",
    "Your potential is limitless, keep pushing your boundaries",
    "beats",
    "rhythm",
    "flow",
    "melody",
    "verse",
    "chorus",
    "bass",
    "studio",
    "lyrics",
    "producer",
    "sample",
    "record",
    "vocals",
    "mic",
    "remix",
    "freestyle",
    "session",
    "jam",
    "soundtrack",
    "orchestra",
    "instrumental",
    "arrangement",
    "bridge",
    "hook",
    "acapella",
    "tempo",
    "bpm",
    "mixing",
    "mastering",
    "harmony",
    "vibe",
    "gig",
    "album",
    "track",
    "concert",
    "tour",
    "venue",
    "DJ",
    "playlist",
    "setlist",
    "soundboard",
    "headphones",
    "subwoofer",
    "tuning",
    "composition",
    "beatbox",
    "diss track",
    "cypher",
    "rap battle",
    "record label",
    "billboard",
    "grammy",
    "platinum",
    "gold record",
    "streaming",
    "chart",
    "jukebox",
    "karaoke",
    "autotune",
    "block",
    "corner",
    "alley",
    "hood",
    "gang",
    "crew",
    "trap",
    "hustle",
    "grind",
    "clique",
    "backstreet",
    "graffiti",
    "bodega",
    "stoop",
    "subway",
    "underground",
    "brick",
    "blockbuster",
    "flashy",
    "gangster",
    "thug",
    "streetwear",
    "sneakers",
    "kicks",
    "chains",
    "bling",
    "fade",
    "buzzcut",
    "dreads",
    "tattoos",
    "lowrider",
    "hooptie",
    "cruise",
    "dice",
    "dominoes",
    "loiter",
    "block party",
    "breakdancing",
    "skate",
    "tag",
    "rep",
    "swagger",
    "ghetto",
    "urban legend",
    "trap house",
    "corner store",
    "double cup",
    "weed",
    "lean",
    "pistol",
    "strap",
    "choppa",
    "draco",
    "molly",
    "perc",
    "gas",
    "zaza",
    "burner",
    "plug",
    "homie",
    "squad",
    "fam",
    "ride or die",
    "battle",
    "dispute",
    "beef",
    "clash",
    "rivalry",
    "showdown",
    "confrontation",
    "verbal sparring",
    "mic wars",
    "diss",
    "shade",
    "comeback",
    "rebuttal",
    "takedown",
    "roast",
    "flame",
    "ether",
    "snap",
    "comeback king",
    "verbal assassin",
    "sharp tongue",
    "bars for days",
    "punchlines",
    "metaphors",
    "similes",
    "wordplay",
    "freestyle",
    "cypher",
    "ring",
    "arena",
    "contender",
    "underdog",
    "champion",
    "knockout",
    "uppercut",
    "jab",
    "combo",
    "spitfire",
    "spit venom",
    "brawler",
    "combat",
    "duel",
    "feud",
    "grudge match",
    "win",
    "loss",
    "draw",
    "one-on-one",
    "throwdown",
    "smackdown",
    "hit 'em up",
    "cutthroat",
    "rap god",
    "wordsmith",
    "lyrical warfare",
    "truth bombs",
    "grenades",
    "lyrical swords",
    "verbal bullets",
    "crossfire",
    "aggression",
    "street cred",
    "call-out",
    "counterattack",
    "offensive",
    "defensive",
    "rounds",
    "judges",
    "crowd control",
    "championship",
    "belt",
    "trophy",
    "spotlight",
    "roaring crowd",
    "boos",
    "cheers",
    "Living life in the spotlight",
    "Paparazzi flashing",
    "Red carpet entrance",
    "Autograph signings",
    "Fan mail",
    "VIP access",
    "All eyes on me",
    "Instant fame",
    "Viral sensation",
    "Sold out tours",
    "Worldwide recognition",
    "Signature swag",
    "Media frenzy",
    "Trending topic",
    "Cover story",
    "Tabloid rumors",
    "Reality show offers",
    "Celebrity endorsements",
    "Social media king",
    "Influencer status",
    "Million followers",
    "Top of the charts",
    "Award-winning",
    "Iconic style",
    "Industry favorite",
    "Star-studded events",
    "Exclusive parties",
    "Private jets",
    "Luxury lifestyle",
    "Brand ambassador",
    "Fashion icon",
    "Billboard topper",
    "Grammy winner",
    "Walk of fame",
    "Blockbuster hits",
    "Movie roles",
    "Talk show appearances",
    "Charity events",
    "Net worth",
    "Billionaire status",
    "Entrepreneurial ventures",
    "Business mogul",
    "Record deal",
    "Platinum albums",
    "Diamonds on the wrist",
    "Designer fits",
    "Public image",
    "Humble beginnings",
    "Fan favorite",
    "Crossover artist",
    "Music legend",
    "Documentary feature",
    "Legacy",
    "Hall of Fame",
    "Cultural impact",
    "Designer labels",
    "Drip too hard",
    "Fresh to death",
    "Streetwear king",
    "High fashion",
    "Tailored suits",
    "Luxury fabrics",
    "Satin and silk",
    "Gold chains",
    "Diamond rings",
    "Iced-out grillz",
    "Leather jackets",
    "Exclusive sneakers",
    "Kicks game proper",
    "Stylish shades",
    "Brand ambassador",
    "Fashion week front row",
    "Custom fits",
    "Bespoke threads",
    "Dripped in Gucci",
    "Rocking Versace",
    "Prada flex",
    "Chanel bags",
    "Louis V everything",
    "Balenciaga steppin'",
    "Off-White collab",
    "Supreme drops",
    "Yeezy boost",
    "Fresh fade",
    "Wavy braids",
    "Dreadlock crown",
    "Street chic",
    "Vogue cover",
    "Runway model",
    "Sartorial splendor",
    "Swagged out",
    "Thrift shop finds",
    "Retro vibes",
    "Vintage flair",
    "Color blocking",
    "Minimalist fits",
    "Statement pieces",
    "Head to toe",
    "Accessorized",
    "Custom kicks",
    "Sneakerhead",
    "Fashion-forward",
    "Style icon",
    "Red bottom heels",
    "Silk scarves",
    "Bucket hats",
    "Varsity jackets",
    "High-end fashion",
    "Luxury boutiques",
    "Street couture",
    "Hip-hop aesthetic",
    "Swag on a hundred",
    "Stylistic genius",
    "Trendsetter",
    "Fashionista",
    "Monochrome look",
    "Athleisure wear",
    "Casual chic",
    "Avant-garde",
    "Dapper Dan",
    "Savile Row",
    "Rodeo Drive",
    "Couture closet",
    "Closet goals",
    "What's good?",
    "No cap",
    "Bet",
    "Flexin'",
    "Lit",
    "Woke",
    "Bussin'",
    "Facts",
    "On God",
    "Keep it 100",
    "Real talk",
    "Word",
    "Salty",
    "High key",
    "Low key",
    "Catch these hands",
    "Slide",
    "Drip",
    "Goat",
    "Gucci",
    "Slay",
    "Vibe check",
    "Mood",
    "It's a vibe",
    "Turnt",
    "Thirsty",
    "Receipts",
    "Stay woke",
    "Fam",
    "Squad",
    "Bruh",
    "Dope",
    "Savage",
    "Finesse",
    "Yeet",
    "Glow up",
    "Ghosted",
    "Shook",
    "Clout",
    "Dab",
    "Wylin'",
    "Extra",
    "Basic",
    "Bless up",
    "Keep it real",
    "No chill",
    "Boujee",
    "Plug",
    "Fire",
    "Flex",
    "Bae",
    "On fleek",
    "Sis",
    "Troll",
    "Boomer",
    "Karen",
    "Viral",
    "Twerk",
    "Snatched",
    "Tea",
    "Shade",
    "Spill the tea",
    "Deadass",
    "Bop",
    "Clout chaser",
    "Bumpin'",
    "Chillax",
    "Kicks",
    "Whip",
    "Glo-up",
    "Jawn",
    "Big mad",
    "Periodt",
    "Woke af",
    "Bougie",
    "Catch a fade",
    "Peep game",
    "On my mama",
    "Run it up",
    "Finesse game",
    "Hit a lick",
    "Run the block",
    "Cuffing season",
    "Get the bag",
    "Faded",
    "Trappin'",
    "Whippin' a Benz",
    "Lambo dreams",
    "Rolls-Royce flex",
    "Riding in style",
    "Custom rims",
    "Butterfly doors",
    "Candy paint",
    "Chrome wheels",
    "Convertible top",
    "Drop top",
    "Luxury leather",
    "Sports car vibes",
    "Engine roaring",
    "Turbocharged",
    "Nitrous boost",
    "Porsche life",
    "Ferrari speed",
    "Audi life",
    "Beamer shine",
    "Caddy cruise",
    "Old-school Chevy",
    "Classic muscle",
    "G-Wagon stuntin'",
    "Tesla torque",
    "Hybrid hustle",
    "Electric slide",
    "SUV comfort",
    "Truck life",
    "Mud tires",
    "All-terrain",
    "Off-road king",
    "Custom exhaust",
    "Tinted windows",
    "GPS guidance",
    "Heated seats",
    "Bluetooth beats",
    "Sound system booming",
    "Spinners on deck",
    "Hydraulics bounce",
    "Neon underglow",
    "License to thrill",
    "Convertible cruisin'",
    "Midnight rider",
    "Speed demon",
    "Racing stripes",
    "Drifting corners",
    "Quarter mile sprint",
    "Spoiler alert",
    "Fast lane living",
    "High-octane",
    "Fuel injected",
    "Roadster rockin'",
    "Limited edition",
    "Luxury SUV",
    "Executive sedan",
    "Fleet of whips",
    "Garage goals",
    "Penthouse suite",
    "Private island",
    "Five-star dining",
    "Michelin star meals",
    "Gold utensils",
    "Imported silk",
    "Egyptian cotton",
    "Private yacht",
    "Exotic car collection",
    "Diamond-studded collar",
    "VIP concierge",
    "Caviar dreams",
    "Custom suits",
    "Personal chauffeur",
    "Gourmet chef",
    "Private jets",
    "First-class flights",
    "Jetsetter lifestyle",
    "Expensive habits",
    "Opulent tastes",
    "Designer everything",
    "High-rise living",
    "Ocean views",
    "Butler service",
    "Custom jewelry",
    "Exotic pets",
    "Purebred dogs",
    "Custom-built mansions",
    "Royal treatment",
    "Black card swipe",
    "Vintage wines",
    "Rare cigars",
    "Monogrammed linens",
    "Gold-plated watches",
    "Luxury auctions",
    "Custom-built anything",
    "Gourmet coffee",
    "Spa retreats",
    "Luxury spas",
    "Cultural artifacts",
    "Fine art collection",
    "Museum-worthy",
    "",
]

# At the end of the file, add this line:
__all__ = ['all_phrases']
